# Generated by Django 3.1.5 on 2021-01-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assertmanage',
            name='fornum',
            field=models.CharField(max_length=128, null=True, verbose_name='循环次数'),
        ),
    ]
