# Generated by Django 3.1.5 on 2021-01-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_assertmanage_fornum'),
    ]

    operations = [
        migrations.AddField(
            model_name='assertmanage',
            name='order',
            field=models.CharField(max_length=32, null=True, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='casemanage',
            name='ifrun',
            field=models.CharField(max_length=64, null=True, verbose_name='是否允许'),
        ),
        migrations.AddField(
            model_name='infuncmanage',
            name='order',
            field=models.CharField(max_length=32, null=True, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='stepmanage',
            name='order',
            field=models.CharField(max_length=32, null=True, verbose_name='序号'),
        ),
    ]
