# Generated by Django 3.1.5 on 2021-02-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210128_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assertmanage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='infuncmanage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stepmanage',
            name='name',
        ),
    ]
