# Generated by Django 3.1.5 on 2021-02-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210201_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemanage',
            name='ifrun',
        ),
        migrations.AddField(
            model_name='casemanage',
            name='np',
            field=models.CharField(max_length=64, null=True, verbose_name='是新增还是更新'),
        ),
    ]
