# Generated by Django 3.1.5 on 2021-02-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210206_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimanage',
            name='log',
            field=models.CharField(max_length=1280, null=True, verbose_name='日志'),
        ),
    ]
